# -*- coding: utf-8 -*-
"""Cheminformatics  Analysis: Functional group profiling of Drug Molecules

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_F-x0d87-qVT69keED1INvmKR3K9Ls5

# Cheminformatics Analysis: Functional Group Profiling of Drug Molecules

### Mount Google Drive
This cell mounts my Google Drive, allowing the notebook to access files stored there. This is necessary to load the dataset from Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Load Dataset
This cell imports the pandas library and loads the `Drugs.csv` file from  Google Drive into a pandas DataFrame named `df`. It then displays the first 5 rows to give you a quick overview of the data.
"""

import pandas as pd

# Define the path to the CSV file in Google Drive
file_path = '/content/drive/MyDrive/Drugs.csv'

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

"""### Import Libraries and Install RDKit
This cell ensures that the `rdkit` library is installed and then imports all necessary Python libraries for data manipulation (`pandas`), plotting (`matplotlib.pyplot`, `seaborn`), and cheminformatics (`rdkit.Chem`).
"""

# Import needed libraries
! pip install rdkit
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from rdkit import Chem

"""### Prepare DataFrame for Analysis
This cell creates a new DataFrame called `readydf` by selecting only the "Compound ID" and "smiles" columns from the original `df`. The `.copy()` method ensures that `readydf` is an independent DataFrame, preventing warnings when modifying it later.
"""

readydf= df[["Compound ID","smiles"]].copy()
readydf.head()

"""### Define SMILES to Molecule Conversion Function
This cell defines a helper function `check_safety_import_mol` that takes a SMILES string as input. It attempts to convert the SMILES string into an RDKit molecule object. If the input is not a valid string or the conversion fails, it returns `None`.
"""

def check_safety_import_mol(smi) :
    if not isinstance(smi, str) or smi.strip() == "" :
        return None
    try:
        mol= Chem.MolFromSmiles(smi)
        return  mol
    except Exception:
        return None

"""### Create Molecule Objects
This cell applies the `check_safety_import_mol` function to the "smiles" column of `readydf`. The resulting RDKit molecule objects (or `None` for invalid SMILES) are stored in a new column called "Mol".
"""

readydf["Mol"] = readydf["smiles"].apply(check_safety_import_mol)
print(readydf[["Compound ID","smiles","Mol"]].head())

"""### Define Functional Group SMARTS Patterns
This cell defines a dictionary named `functional_groups`. The keys are common names of functional groups (e.g., "Hydroxyl", "Ketone"), and the values are their corresponding SMARTS (SMiles ARbitrary Target Specification) patterns. These patterns are used by RDKit to identify specific substructures in molecules.
"""

functional_groups = {
      "Primary_Amine": "[NH2]",
      "Hydroxyl": "[OH]",
      "Carboxylic_Acid": "C(=O)[OH]",
      "Ester": "C(=O)O[#6]",
      "Amide": "C(=O)[NH]",
      "Ketone": "[#6]C(=O)[#6]",
      "Aromatic_Ring": "c1ccccc1",
      "Halogen": "[F,Cl,Br,I]"
}

"""### Define Functional Group Detection Function
This cell defines the `find_all_functional_groups` function. It takes an RDKit molecule object and the `functional_groups` dictionary as input. For each functional group in the dictionary, it checks if the molecule contains that substructure using `Chem.MolFromSmarts` and `mol.HasSubstructMatch`. It returns a list of names of all functional groups found in the molecule.
"""

def find_all_functional_groups(mol , functional_groups) :

     found_groups= [ ]
     for name, fg in functional_groups.items():
         fgstru = Chem.MolFromSmarts(fg)
         if fgstru is None :
            continue
         has_sub = mol.HasSubstructMatch(fgstru)
         if has_sub :
            found_groups.append(name)
     return found_groups

"""### Identify Functional Groups in Compounds
This cell applies the `find_all_functional_groups` function to each molecule in the "Mol" column of `readydf`. The list of functional groups identified for each compound is then stored in a new column called "Functional_Groups".
"""

readydf["Functional_Groups"] = readydf["Mol"].apply(lambda m : find_all_functional_groups(m , functional_groups))

print(readydf[["Compound ID" , "smiles", "Mol" , "Functional_Groups"]].head(10))

"""### Count Functional Group Occurrences
This cell first 'explodes' the list of functional groups in the "Functional_Groups" column so that each individual functional group gets its own row. Then, it counts the occurrences of each unique functional group and stores these counts in a new DataFrame called `group_counts`.
"""

all_groups = readydf["Functional_Groups"].explode()
group_counts = all_groups.value_counts().reset_index()
group_counts.columns= ["Functional_Groups", "count"]
print(group_counts)

"""### Visualize Functional Group Counts
This cell generates a bar plot using `seaborn` and `matplotlib` to visualize the counts of each functional group. It sets the plot's title and axis labels, ensures a tight layout, saves the plot as a PNG image, and then displays it.
"""

plt.figure (figsize=(10, 8))

sns.barplot(x="Functional_Groups" , y="count" , data=group_counts , color="green")
plt.title("Count of each Functional group" , fontsize=22 , weight="bold")
plt.xlabel("Functional Group" , fontsize= 18)
plt.ylabel("Count" , fontsize= 18)
plt.tight_layout()

plt.savefig("Count of each Functional group" ,dpi=300 )
plt.show()

"""### Export Final Analysis Report
This cell saves the `readydf` DataFrame, which now includes the identified functional groups, to a CSV file named `Final_Analysis_Report.csv`. The `index=False` argument prevents pandas from writing the DataFrame index as a column in the CSV. It also prints a confirmation message and displays the head of the DataFrame.
"""

readydf.to_csv("Final_Analysis_Report.csv", index=False)

print("DataFrame saved to Final_Analysis_Report.csv")
print(readydf.head())

"""### Download Analysis Report
This cell uses the `files.download` function from `google.colab` to initiate the download of the `Final_Analysis_Report.csv` file directly to my local machine.
"""

from google.colab import files
files.download('Final_Analysis_Report.csv')